<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Meu Mapa GPS</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>Mapa dos Meus Lugares</h1>
  </header>

  <main>
    <div id="mapa"></div>
  </main>

  <script src="script.js"></script>
</body>
</html>
